
package project2;

import java.awt.Color;
import javax.swing.JOptionPane;

public class Practise2 extends javax.swing.JFrame {
    int c=0;
    int playerxPoint=0,plyer0Point=0;
    
   
    public Practise2() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clkbtn1 = new javax.swing.JButton();
        clkbtn7 = new javax.swing.JButton();
        clkbtn4 = new javax.swing.JButton();
        clkbtn2 = new javax.swing.JButton();
        clkbtn5 = new javax.swing.JButton();
        clkbtn8 = new javax.swing.JButton();
        clkbtn9 = new javax.swing.JButton();
        clkbtn6 = new javax.swing.JButton();
        clkbtn3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pointX = new javax.swing.JTextField();
        point0 = new javax.swing.JTextField();
        resetbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        showWinner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        clkbtn1.setBackground(java.awt.Color.lightGray);
        clkbtn1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        clkbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkbtn1ActionPerformed(evt);
            }
        });

        clkbtn7.setBackground(java.awt.Color.lightGray);
        clkbtn7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        clkbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkbtn7ActionPerformed(evt);
            }
        });

        clkbtn4.setBackground(java.awt.Color.lightGray);
        clkbtn4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        clkbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkbtn4ActionPerformed(evt);
            }
        });

        clkbtn2.setBackground(java.awt.Color.lightGray);
        clkbtn2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        clkbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkbtn2ActionPerformed(evt);
            }
        });

        clkbtn5.setBackground(java.awt.Color.lightGray);
        clkbtn5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        clkbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkbtn5ActionPerformed(evt);
            }
        });

        clkbtn8.setBackground(java.awt.Color.lightGray);
        clkbtn8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        clkbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkbtn8ActionPerformed(evt);
            }
        });

        clkbtn9.setBackground(java.awt.Color.lightGray);
        clkbtn9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        clkbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkbtn9ActionPerformed(evt);
            }
        });

        clkbtn6.setBackground(java.awt.Color.lightGray);
        clkbtn6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        clkbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkbtn6ActionPerformed(evt);
            }
        });

        clkbtn3.setBackground(java.awt.Color.lightGray);
        clkbtn3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        clkbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkbtn3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Player X");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel4.setText("Player 0");

        pointX.setEditable(false);
        pointX.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        pointX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pointX.setText("0");

        point0.setEditable(false);
        point0.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        point0.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        point0.setText("0");

        resetbtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        showWinner.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        showWinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        showWinner.setText("Let's Play");
        showWinner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showWinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pointX)
                            .addComponent(point0, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pointX, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(point0))
                .addGap(18, 18, 18)
                .addComponent(showWinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clkbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clkbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clkbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clkbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clkbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clkbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clkbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clkbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clkbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clkbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(clkbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clkbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clkbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(clkbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clkbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clkbtn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clkbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clkbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear(){
        clkbtn1.setText("");
        clkbtn1.setBackground(Color.LIGHT_GRAY);
        clkbtn2.setText("");
        clkbtn2.setBackground(Color.LIGHT_GRAY);
        clkbtn3.setText("");
        clkbtn3.setBackground(Color.LIGHT_GRAY);
        clkbtn4.setText("");
        clkbtn4.setBackground(Color.LIGHT_GRAY);
        clkbtn5.setText("");
        clkbtn5.setBackground(Color.LIGHT_GRAY);
        clkbtn6.setText("");
        clkbtn6.setBackground(Color.LIGHT_GRAY);
        clkbtn7.setText("");
        clkbtn7.setBackground(Color.LIGHT_GRAY);
        clkbtn8.setText("");
        clkbtn8.setBackground(Color.LIGHT_GRAY);
        clkbtn9.setText("");
        clkbtn9.setBackground(Color.LIGHT_GRAY);
        showWinner.setText("Let's Play");
        c=0;
    }
    private void check(){
        if(clkbtn1.getText()=="X" && clkbtn2.getText()=="X" && clkbtn3.getText()=="X"){
            
            //String titleBar="Winner";
                
            int x =Integer.parseInt(pointX.getText());
            x++;
            String s=Integer.toString(x);
            pointX.setText(s);
            
            showWinner.setText("X has Won");
            //JOptionPane.showMessageDialog(null, "X has Won", titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn1.setBackground(Color.GREEN);
            clkbtn2.setBackground(Color.GREEN);
            clkbtn3.setBackground(Color.GREEN);
        }
        else if(clkbtn1.getText()=="X" && clkbtn4.getText()=="X" && clkbtn7.getText()=="X"){
            //String titleBar="Winner";
             
            int x =Integer.parseInt(pointX.getText());
            x++;
            String s=Integer.toString(x);
            pointX.setText(s);
            showWinner.setText("X has Won");
            //JOptionPane.showMessageDialog(null, "X has Won",titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn1.setBackground(Color.GREEN);
            clkbtn4.setBackground(Color.GREEN);
            clkbtn7.setBackground(Color.GREEN);
        }
        else if(clkbtn1.getText()=="X" && clkbtn5.getText()=="X" && clkbtn9.getText()=="X"){
            //String titleBar="Winner";
             
            int x =Integer.parseInt(pointX.getText());
            x++;
            String s=Integer.toString(x);
            pointX.setText(s);
            showWinner.setText("X has Won");
            //JOptionPane.showMessageDialog(null, "X has Won", titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn1.setBackground(Color.GREEN);
            clkbtn5.setBackground(Color.GREEN);
            clkbtn9.setBackground(Color.GREEN);
        }
        else if(clkbtn2.getText()=="X" && clkbtn5.getText()=="X" && clkbtn8.getText()=="X"){
            //String titleBar="Winner";
               
            int x =Integer.parseInt(pointX.getText());
            x++;
            String s=Integer.toString(x);
            pointX.setText(s);
            showWinner.setText("X has Won");
            //JOptionPane.showMessageDialog(null, "X has Won", titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn2.setBackground(Color.GREEN);
            clkbtn5.setBackground(Color.GREEN);
            clkbtn8.setBackground(Color.GREEN);
        }
        else  if(clkbtn4.getText()=="X" && clkbtn5.getText()=="X" && clkbtn6.getText()=="X"){
            //String titleBar="Winner";
               
            int x =Integer.parseInt(pointX.getText());
            x++;
            String s=Integer.toString(x);
            pointX.setText(s);
            showWinner.setText("X has Won");
            //JOptionPane.showMessageDialog(null, "X has Won", titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn4.setBackground(Color.GREEN);
            clkbtn5.setBackground(Color.GREEN);
            clkbtn6.setBackground(Color.GREEN);
        }
        else if(clkbtn3.getText()=="X" && clkbtn6.getText()=="X" && clkbtn9.getText()=="X"){
            //String titleBar="Winner";
           
            int x =Integer.parseInt(pointX.getText());
            x++;
            String s=Integer.toString(x);
            pointX.setText(s);
            showWinner.setText("X has Won");
            //JOptionPane.showMessageDialog(null, "X has Won",  titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn3.setBackground(Color.GREEN);
            clkbtn6.setBackground(Color.GREEN);
            clkbtn9.setBackground(Color.GREEN);
        }
        
        else if(clkbtn3.getText()=="X" && clkbtn5.getText()=="X" && clkbtn7.getText()=="X"){
            //String titleBar="Winner";
             
            int x =Integer.parseInt(pointX.getText());
            x++;
            String s=Integer.toString(x);
            pointX.setText(s);
            showWinner.setText("X has Won");
            //JOptionPane.showMessageDialog(null, "X has Won", titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn3.setBackground(Color.GREEN);
            clkbtn5.setBackground(Color.GREEN);
            clkbtn7.setBackground(Color.GREEN);
        }
        else if(clkbtn7.getText()=="X" && clkbtn8.getText()=="X" && clkbtn9.getText()=="X"){
            //String titleBar="Winner";
             
            int x =Integer.parseInt(pointX.getText());
            x++;
            String s=Integer.toString(x);
            pointX.setText(s);
            showWinner.setText("X has Won");
            //JOptionPane.showMessageDialog(null, "X has Won", titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn7.setBackground(Color.GREEN);
            clkbtn8.setBackground(Color.GREEN);
            clkbtn9.setBackground(Color.GREEN);
        }
        else if(clkbtn1.getText()=="0" && clkbtn2.getText()=="0" && clkbtn3.getText()=="0"){
            //String titleBar="Winner";
             
            int x =Integer.parseInt(point0.getText());
            x++;
            String s=Integer.toString(x);
            point0.setText(s);
            showWinner.setText("0 has Won");
            //JOptionPane.showMessageDialog(null, "0 has Won",titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn1.setBackground(Color.GREEN);
            clkbtn2.setBackground(Color.GREEN);
            clkbtn3.setBackground(Color.GREEN);
        }
        else if(clkbtn1.getText()=="0" && clkbtn4.getText()=="0" && clkbtn7.getText()=="0"){
            //String titleBar="Winner";
             
            int x =Integer.parseInt(point0.getText());
            x++;
            String s=Integer.toString(x);
            point0.setText(s);
            showWinner.setText("0 has Won");
            //JOptionPane.showMessageDialog(null, "0 has Won",titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn1.setBackground(Color.GREEN);
            clkbtn4.setBackground(Color.GREEN);
            clkbtn7.setBackground(Color.GREEN);
        }
        else if(clkbtn1.getText()=="0" && clkbtn5.getText()=="0" && clkbtn9.getText()=="0"){
            //String titleBar="Winner";
            
            int x =Integer.parseInt(point0.getText());
            x++;
            String s=Integer.toString(x);
            point0.setText(s);
            showWinner.setText("0 has Won");
            //JOptionPane.showMessageDialog(null, "0 has Won",  titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn1.setBackground(Color.GREEN);
            clkbtn5.setBackground(Color.GREEN);
            clkbtn9.setBackground(Color.GREEN);
        }
        else if(clkbtn2.getText()=="0" && clkbtn5.getText()=="0" && clkbtn8.getText()=="0"){
            //String titleBar="Winner";
                
            int x =Integer.parseInt(point0.getText());
            x++;
            String s=Integer.toString(x);
            point0.setText(s);
            showWinner.setText("0 has Won");
            //JOptionPane.showMessageDialog(null, "0 has Won",  titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn2.setBackground(Color.GREEN);
            clkbtn5.setBackground(Color.GREEN);
            clkbtn8.setBackground(Color.GREEN);
        }
        
        else  if(clkbtn4.getText()=="0" && clkbtn5.getText()=="0" && clkbtn6.getText()=="0"){
            //String titleBar="Winner";
                
            int x =Integer.parseInt(point0.getText());
            x++;
            String s=Integer.toString(x);
            point0.setText(s);
            showWinner.setText("0 has Won");
            //JOptionPane.showMessageDialog(null, "0 has Won",  titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn4.setBackground(Color.GREEN);
            clkbtn5.setBackground(Color.GREEN);
            clkbtn6.setBackground(Color.GREEN);
        }
        else if(clkbtn3.getText()=="0" && clkbtn6.getText()=="0" && clkbtn9.getText()=="0"){
            //String titleBar="Winner";
             
            int x =Integer.parseInt(point0.getText());
            x++;
            String s=Integer.toString(x);
            point0.setText(s);
            showWinner.setText("0 has Won");
            //JOptionPane.showMessageDialog(null, "0 has Won", titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn3.setBackground(Color.GREEN);
            clkbtn6.setBackground(Color.GREEN);
            clkbtn9.setBackground(Color.GREEN);
        }
        else if(clkbtn3.getText()=="0" && clkbtn5.getText()=="0" && clkbtn7.getText()=="0"){
            //String titleBar="Winner";
             
            int x =Integer.parseInt(point0.getText());
            x++;
            String s=Integer.toString(x);
            point0.setText(s);
            showWinner.setText("0 has Won");
            //JOptionPane.showMessageDialog(null, "0 has Won",  titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn3.setBackground(Color.GREEN);
            clkbtn5.setBackground(Color.GREEN);
            clkbtn7.setBackground(Color.GREEN);
        }
        else if(clkbtn7.getText()=="0" && clkbtn8.getText()=="0" && clkbtn9.getText()=="0"){
            //String titleBar="Winner";
             
            int x =Integer.parseInt(point0.getText());
            x++;
            String s=Integer.toString(x);
            point0.setText(s);
            showWinner.setText("0 has Won");
            //JOptionPane.showMessageDialog(null, "0 has Won",  titleBar, JOptionPane.INFORMATION_MESSAGE);
            clkbtn7.setBackground(Color.GREEN);
            clkbtn8.setBackground(Color.GREEN);
            clkbtn9.setBackground(Color.GREEN);
        }
        else if(!clkbtn1.getText().isEmpty() && !clkbtn2.getText().isEmpty() && !clkbtn3.getText().isEmpty()
                && !clkbtn4.getText().isEmpty() && !clkbtn5.getText().isEmpty() && !clkbtn6.getText().isEmpty()
                && !clkbtn7.getText().isEmpty() && !clkbtn8.getText().isEmpty() && !clkbtn9.getText().isEmpty()){
            //JOptionPane.showMessageDialog(null, "Match is Drawn",  "Draw", JOptionPane.INFORMATION_MESSAGE);
            showWinner.setText("Match Drawn");
        }
    }
    private void clkbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkbtn1ActionPerformed
        if(clkbtn1.getText().isEmpty()){
        if(c%2==0){    
            clkbtn1.setText("X");
            c++;
            check();
        }
        else{
            clkbtn1.setText("0");
            c++;
            check();
        }
        }
    }//GEN-LAST:event_clkbtn1ActionPerformed

    private void clkbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkbtn3ActionPerformed
        if(clkbtn3.getText().isEmpty()){
        if(c%2==0){    
            clkbtn3.setText("X");
            c++;
            check();
      
        }
        else{
            clkbtn3.setText("0");
            c++;
            check();
        }
        }
    }//GEN-LAST:event_clkbtn3ActionPerformed

    private void clkbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkbtn2ActionPerformed
        if(clkbtn2.getText().isEmpty()){
        if(c%2==0){    
            clkbtn2.setText("X");
            c++;
            check();
        }
        else{
            clkbtn2.setText("0");
            c++;
            check();
        }
        }
    }//GEN-LAST:event_clkbtn2ActionPerformed

    private void clkbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkbtn4ActionPerformed
        if(clkbtn4.getText().isEmpty()){
        if(c%2==0){    
            clkbtn4.setText("X");
            c++;
            check();
        }
        else{
            clkbtn4.setText("0");
            c++;
            check();
        }
        }
    }//GEN-LAST:event_clkbtn4ActionPerformed

    private void clkbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkbtn5ActionPerformed
        if(clkbtn5.getText().isEmpty()){
        if(c%2==0){    
            clkbtn5.setText("X");
            c++;
            check();
        }
        else{
            clkbtn5.setText("0");
            c++;
            check();
        }
        }
    }//GEN-LAST:event_clkbtn5ActionPerformed

    private void clkbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkbtn6ActionPerformed
        if(clkbtn6.getText().isEmpty()){
        if(c%2==0){    
            clkbtn6.setText("X");
            c++;
            check();
        }
        else{
            clkbtn6.setText("0");
            c++;
            check();
        }
        }
    }//GEN-LAST:event_clkbtn6ActionPerformed

    private void clkbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkbtn7ActionPerformed
        if(clkbtn7.getText().isEmpty()){
        if(c%2==0){    
            clkbtn7.setText("X");
            c++;
            check();
        }
        else{
            clkbtn7.setText("0");
            c++;
            check();
        }
        }
    }//GEN-LAST:event_clkbtn7ActionPerformed

    private void clkbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkbtn8ActionPerformed
        if(clkbtn8.getText().isEmpty()){
        if(c%2==0){    
            clkbtn8.setText("X");
            c++;
            check();
        }
        else{
            clkbtn8.setText("0");
            c++;
            check();
        }
        }
    }//GEN-LAST:event_clkbtn8ActionPerformed

    private void clkbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkbtn9ActionPerformed
        if(clkbtn9.getText().isEmpty()){
        if(c%2==0){    
            clkbtn9.setText("X");
            c++;
            check();
        }
        else{
            clkbtn9.setText("0");
            c++;
            check();
        }
        }
    }//GEN-LAST:event_clkbtn9ActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_resetbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practise2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practise2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clkbtn1;
    private javax.swing.JButton clkbtn2;
    private javax.swing.JButton clkbtn3;
    private javax.swing.JButton clkbtn4;
    private javax.swing.JButton clkbtn5;
    private javax.swing.JButton clkbtn6;
    private javax.swing.JButton clkbtn7;
    private javax.swing.JButton clkbtn8;
    private javax.swing.JButton clkbtn9;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField point0;
    private javax.swing.JTextField pointX;
    private javax.swing.JButton resetbtn;
    private javax.swing.JLabel showWinner;
    // End of variables declaration//GEN-END:variables
}
